### ISSUE TITLE
rake console method missing

### ISSUE THREAD

**Issue by simque** [learn-co-curriculum/mechanics-of-migrations#11]
After running `rake db:migrate` and extending our Artist class with `ActiveRecord::Base`, the lab proceeds with the statement, "To test it out, let's use the raketask rake console, which we're created in the Rakefile," however, this README did not offer a code along that would have the reader practice setting up the console method within the Rakefile.  Therefore, when rake console is run an error message appears advising, "rake aborted! Don't know how to build task 'console.'"

I was able to get the lab working by returning to a previous lab and copying the code for the `:console` and `:environment` raketasks, but it would be great if there were an explicit code along in this lab to review and solidify for the reader the information that was touched on in the previous "Intro to Rake" lab.

**Comment by AnnJohn** [comment]
thanks @simque. We'll fix this as soon as we can.
