### ISSUE TITLE
Weird order to this and previous lessons

### ISSUE THREAD

**Issue by authorbeard** [learn-co-curriculum/mechanics-of-migrations#16]
This and the Intro to Rake would have been much, much more useful before the ActiveRecord CRUD lab. I wound up figuring that out because I read the ActiveRecord documentation and worked through the lab that way, but I got that before I got this and Rake and was more than a little bewildered. And got some strange looks when I was asking questions about that lab that these last two would have answered.

**Comment by AnnJohn** [comment]
hi @authorbeard we moved the order of the ActiveRecord Crud lab since yes, it was super confusing. 

Thank you!
