### ISSUE TITLE
Suggest we ask people to code along

### ISSUE THREAD

**Issue by PeterBell** [learn-co-curriculum/mechanics-of-migrations#19]
It might be a good idea to more explicitly ask people to fork and clone the repo and to code along. Wondering if in an ideal world we might even be able to add some basic specs to validate successful completion . . .

**Comment by PeterBell** [comment]
cc @genericgirl who raised this

**Comment by AnnJohn** [comment]
@jjseymour this would require you to most likely write specs so it's a relatively big fix. But if you want to take the opp to practice writing tests, this could be a good exercise.

**Comment by pletcher** [comment]
@jjseymour added a code-along and some tests in https://github.com/learn-co-curriculum/mechanics-of-migrations/commit/d9835267fed33d68c409129ab09f981c790dac93
