### ISSUE TITLE
Should we need to write a SQL statement when we already have a rake migration for it?

### ISSUE THREAD

**Issue by BrunoBoehm** [learn-co-curriculum/mechanics-of-migrations#29]
Hey, 
when I read the part below it seems to me we don't need to do this SQL statement.
Indeed we've already made a migration file for creating the table, and run that rake task with db:migrate.
Also the column names are note the same (in the migration we have :name, :genre, :age, :hometown - no mention of :length).

Discussing with @ivalentine it looked to us that this section shouldn't be part of the lesson?

Thanks for your feedback!

> 4) Take a look at artist.rb. Let's create an Artist class.
> # artist.rb
>  
> class Artist
> end
> Next, we'll extend the class with ActiveRecord::Base
> # artist.rb
>  
> class Artist < ActiveRecord::Base
> end
> Last, we need to create our artists table with SQL
> # artist.rb
>  
> class Artist < ActiveRecord::Base
>   def self.create_table
>     sql = <<-SQL
>     CREATE TABLE IF NOT EXISTS songs (
>       id INTEGER PRIMARY KEY,
>       title TEXT,
>       length INTEGER
>     )
>     SQL
>  
>     ActiveRecord::Base.connection.execute(sql)
>   end
> end
> To test it out, let's use the rake task rake console, which we've created in the Rakefile.

**Comment by gj** [comment]
Fixed by a PR that was long-overdue for merging. Thanks for contributing @BrunoBoehm !
