### ISSUE TITLE
Need to include db file to access

### ISSUE THREAD

**Issue by survivingknowledge** [learn-co-curriculum/mechanics-of-migrations#34]
Currently doing lessons on WIndows machine where it stores the labs in users directory. When trying to create a db file, using touch <>.db or sqlite3 it doesn't have necessary permissions to do so. If you include a file, it can access it then manipulate the file as in the next lesson successfully.

**Comment by pickledyamsman** [comment]
@aturkewi This is still an issue as of 3/1/2017. The migrations will not run because the database is never created even with rake commands.

**Comment by aturkewi** [comment]
@survivingknowledge and @pickledyamsman could one of you update this with a little more info?

I tried doing `touch something.db` and `touch something-else.sqlite3` on a windows machine with not problems.
What exactly is the error you are seeing? Are you able to log in as an admin to do this lab? What version of the IDE are you using and what version of windows are you on?

**Comment by pickledyamsman** [comment]
@aturkewi This seems to only be an issue in the IDE, on a local environment this worked fine. When running the migrations I get this output.

rake aborted!                                                                                                                 
SQLite3::CantOpenException: unable to open database file                                                                      
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/connection_adapters/sqlite3_adapter.rb:27:in `initial
ize'                                                                                                                          
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/connection_adapters/sqlite3_adapter.rb:27:in `new'   
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/connection_adapters/sqlite3_adapter.rb:27:in `sqlite3
_connection'                                                                                                                  
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:721:i
n `new_connection'                                                                                                            
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:765:i
n `checkout_new_connection'                                                                                                   
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:744:i
n `try_to_checkout_new_connection'                                                                                            
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:705:i
n `acquire_connection'                                                                                                        
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:501:i
n `checkout'                                                                                                                  
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:i
n `connection'        
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:875:i
n `retrieve_connection'                                                                                                       
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/connection_handling.rb:128:in `retrieve_connection'  
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/connection_handling.rb:91:in `connection'            
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/migration.rb:1099:in `initialize'                    
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/migration.rb:1005:in `new'                           
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/migration.rb:1005:in `up'                            
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/migration.rb:983:in `migrate'                        
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/tasks/database_tasks.rb:161:in `migrate'             
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <t
op (required)>'                                                                                                               
/usr/local/rvm/gems/ruby-2.3.1/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'                                             
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'                                                         
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'                                                       
Tasks: TOP => db:migrate                                                                                                      
(See full trace by running task with --trace)    

This happens after adding the code to config/environment.rb, artist.rb, and db/migrate/01_create_artists.rb. It looks like it might be a permissions issue from some stackoverflow searching.

**Comment by aturkewi** [comment]
So I added the code to create the DB and ran `rake db:migrate`. The `artist.sqlite` db was created no problem. I tested this from the Learn IDE in window and in Mac.

Here is the code that I tested with: https://github.com/aturkewi/mechanics-of-migrations-v-000/releases/tag/v1 (I know releases isn't quite the right tool to use for this... but didn't want to mess with tags at the moment). 

If this is a permissions problem, can you try running this as admin?

And @drewprice I'm going to tag you in here in case you have any thoughts on this :)

**Comment by gj** [comment]
Should be all cleared up thanks to the tip from @DakotaLMartinez about ensuring that students in the IDE use the `mkdir` command.

Let me know if you still have people running into issues @aturkewi @pickledyamsman

**Comment by gj** [comment]
Closing with https://github.com/learn-co-curriculum/mechanics-of-migrations/commit/adaadf9b87fa0f0310f36279bfac3abaa0555a83.

Reopen if the issue appears again. 🙂
