### ISSUE TITLE
potential legal issues 

### ISSUE THREAD

**Issue by ode-to-the-code** [learn-co-curriculum/mechanics-of-migrations#38]
these paragraphs in the lab have the exact text from the Ruby on Rails Guides website:

Migrations are a convenient way for you to alter your database in a structured and organized manner. You could edit fragments of SQL by hand but you would then be responsible for telling other developers that they need to go and run them. You’d also have to keep track of which changes need to be run against the production machines next time you deploy.

Migrations also allow you to describe these transformations using Ruby. The great thing about this is that (like most of Active Record’s functionality) it is database independent: you don’t need to worry about the precise syntax of CREATE TABLE any more than you worry about variations on SELECT * (you can drop down to raw SQL for database specific features). For example you could use SQLite3 in development, but MySQL in production.

http://guides.rubyonrails.org/v3.2.8/migrations.html

**Comment by gj** [comment]
@ode-to-the-code thanks so much for catching this!

@joshuabamboo are there any other lessons where this might've happened? Sorry for the random ping!

**Comment by joshuabamboo** [comment]
@gj Thanks for the fix! My fault. We were pumping out content like crazy during that period, so it is possible. But probably not. That one just slipped through the cracks.

**Comment by gj** [comment]
@joshuabamboo haha, I hear ya
