### ISSUE TITLE
confusing paragraph

### ISSUE THREAD

**Issue by williamhancharek** [learn-co-curriculum/mechanics-of-migrations#42]
In the migrate directory, create a file called 01_create_artists.rb (we'll talk about why we added the 01 later). mechanics-of-migrations-v-000/ config/ environment.rb db/ migrate/ 01_create_artists.rb spec/ artist_spec.rb spec_helper.rb .gitignore .learn .rspec artist.rb CONTRIBUTING.md Gemfile Gemfile.lock LICENSE.md Rakefile README.md

--> this section is confusing.  It seemed at first you wanted me to create a bunch of files, named mechanics-of-migrations-v-000/config/environment.rb
db/migrate/01_create_artists.rb spec 
etc etc..

**Comment by sgharms** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
