### ISSUE TITLE
extra text in body

### ISSUE THREAD

**Issue by srolandmarshall** [learn-co-curriculum/mechanics-of-migrations#43]
weird text in the 3rd pt under "Setting Up Your Migration"

`mechanics-of-migrations-v-000/ config/ environment.rb db/ migrate/ 01_create_artists.rb spec/ artist_spec.rb spec_helper.rb .gitignore .learn .rspec artist.rb CONTRIBUTING.md Gemfile Gemfile.lock LICENSE.md Rakefile README.md`

**Comment by sgharms** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
