### ISSUE TITLE
Section "Setting up your migration" Step 3 - has copy/paste error

### ISSUE THREAD

**Issue by mrahman1** [learn-co-curriculum/mechanics-of-migrations#46]
reads:
In the migrate directory, create a file called 01_create_artists.rb (we'll talk about why we added the 01 later). **mechanics-of-migrations-v-000/ config/ environment.rb db/ migrate/ 01_create_artists.rb spec/ artist_spec.rb spec_helper.rb .gitignore .learn .rspec artist.rb CONTRIBUTING.md Gemfile Gemfile.lock LICENSE.md Rakefile README.md**

bolded part looks like an error

**Comment by sgharms** [comment]
Fixed! Thanks!
