### ISSUE TITLE
Creating a Table section is confusing

### ISSUE THREAD

**Issue by lizbur10** [learn-co-curriculum/mechanics-of-migrations#47]
The wording of this section is misleading: it describes how we used to create tables before using ActiveRecord::Migration, and says "First, we'd have to connect to a database" and "Then, we'd create our table using SQL." This implies that create_table replaces both steps: it is not clear that you still need to add the code to establish the connection (or that it should be placed in the environment.rb file) and that the create_table method only replaces the SQL code.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#52. We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team

**Comment by maxwellbenton** [comment]
Hi @lizbur10,

Thank you for providing this feedback. We've updated this lesson's readme and have added content to the table creation section to better explain the transition between using SQL directly and using migrations.

Thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced. 💙
