### ISSUE TITLE
Difficult to Follow

### ISSUE THREAD

**Issue by alyssawatsonlee** [learn-co-curriculum/mechanics-of-migrations#49]
This readme is very difficult to follow.

**Comment by sgharms** [comment]
Hi there,

Would you mind providing a bit more detail about the issue? Things that are especially useful:
- An expanded explanation of what's going on.
- Steps to reproduce the issue.
- Details about your environment.
  + What's your operating system? Which version?
  + Are you using the Learn IDE or a local development environment?
- A [stack trace](https://en.wikipedia.org/wiki/Stack_trace) of any errors.

Thanks! 💙

**Comment by sgharms** [comment]
@alyssaswatson Let me know if you can provide more insight into this. I'd love to take your direction, but am unsure how to proceed. Please reopen when you can provide some specifics. Thanks!
