### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by curiositypaths** [learn-co-curriculum/mechanics-of-migrations#52]
PROBLEM: Clarify creating a table section
NOTIFY: @lizbur10

PROBLEM: Clarify what functionality is inherited from ActiveRecord::Migration
NOTIFY: @katieLars

**Comment by maxwellbenton** [comment]
Clarified section on creating a table - Both issues related to confusion surrounding a code snippet of SQL code, which is not ultimately used, but replaced by migrations. The use of migrations in place of using raw SQL has been clarified in the lesson. Additional changes have been made to point out the Active Record Rails versioning system on migrations ([4.2])
