### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by hysan** [learn-co-curriculum/mechanics-of-migrations#53]
Students are receiving this warning when running `rake db:migrate`:

```
DEPRECATION WARNING: Directly inheriting from ActiveRecord::Migration is deprecated. Please specify the Rails release the migration was written for:

 class CreateArtists < ActiveRecord::Migration[4.2] (called from load at /Users/marielschlaefer/.rvm/gems/ruby-2.3.3/bin/rake:23)
== 1 CreateArtists: migrating =================================================
-- create_table(:artists, {})
  -> 0.0009s
== 1 CreateArtists: migrated (0.0010s) ========================================
```

**Comment by cjbrock** [comment]
Hi @hysan! This is just a warning, not an error. You can fix this error by adding [4.2] after the word Migration when you run your migrations. If you encounter things like this when you're running through lessons, a good thing to do is to google them to see what exactly is happening. This will give you a deeper understanding of how migrations and ActiveRecord work together, and why it's asking you to specify a version of ActiveRecord in the first place. As a professional developer, you're going to run into deprecation warnings a lot, and most of the time you're going to need to make a judgement call about whether they are serious or not. In this case, it's safe to move past it. Thank you for letting us know - we'll update the lab so it stops happening. 
// <3 Corinna
