### ISSUE TITLE
Warning when using rake console

### ISSUE THREAD

**Issue by hysan** [learn-co-curriculum/mechanics-of-migrations#54]
Students are getting the following warning when running `rake console`:

```
irb: warn: can't alias context from irb_context.
2.3.3 :001 > exit
```

I've told them to replace the irb command with Pry.start for now as I'm unsure if that warning will cause issues later on.

**Comment by cjbrock** [comment]
Hi @hysan! Thank you for letting us know. Without a little more information, this is a hard issue to diagnose. I'd recommend that if students are having issues getting `rake console` to run, then they hop on Ask A Question and partner with a Technical Coach. It doesn't seem to be an issue with the curriculum, but more of an issue with an environment. 
Thanks!
// Corinna
