### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by cjbrock** [learn-co-curriculum/mechanics-of-migrations#56]
PROBLEM: Some students have a newer version of rake installed (12.x.x) whereas this lab asks for 11.2.2. I updated my rake gem to try and reproduce this, but could not. However, I have seen a student's environment where it was not possible to run any rake commands without using the workaround of `bundle exec rake <command>`.
SOLUTION: Add in a lesson about bundle exec and how it works, and why we need it
NOTIFY: @hysan

**Comment by maxwellbenton** [comment]
Added additional messaging about the use of `bundle exec` and what it does in this lab, as well as reminders in multiple locations to ensure students know to prepend the rake commands if they are running into this error.
