### ISSUE TITLE
missing  info in read me 

### ISSUE THREAD

**Issue by gbs4ever** [learn-co-curriculum/mechanics-of-migrations#58]
**this should be added to this lesson also as it does throw the error** 

NOTE: As of Active Record 5.x, we can no longer inherit directly from ActiveRecord::Migration and must instead specify which version of Active Record / Rails the migration was written for. If we were writing a migration for Active Record 5.1, we would inherit from ActiveRecord::Migration[5.1]. Don't worry too much about this until you get to the Rails section. Until then, if you encounter an error like this...

StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:
 
  class CreateDogs < ActiveRecord::Migration[4.2]
...simply add [4.2] to the end of ActiveRecord::Migration, exactly as the error message instructs.

Here's a simple example of the create_table method in action:

**Comment by maxwellbenton** [comment]
Hi @gbs4ever,

Thank you for providing this feedback. We've updated this lesson's readme to include messaging about migration syntax similar to what you have suggested and believe this issue should be resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙

**Comment by gbs4ever** [comment]
Yes, it may have been frustrating but it helped me grow in my coding by
being able to figure out the issue and come up with possible solutions.

All the best
Sim Greenbaum
