### ISSUE TITLE
ActiveRecord Migration Instructions

### ISSUE THREAD

**Issue by ryansise** [learn-co-curriculum/mechanics-of-migrations#60]
It would be extremely helpful if you copied the following text from the readme in the "Writing Your Own Migrations" lab into this lab's readme:

## Active Record 5.x migration syntax update

***NOTE***: As of Active Record 5.x, we can no longer inherit directly from `ActiveRecord::Migration` and must instead specify which version of Active Record / Rails the migration was written for. If we were writing a migration for Active Record 5.1, we would inherit from `ActiveRecord::Migration[5.1]`. Don't worry too much about this until you get to the Rails section. Until then, if you encounter an error like this...
...simply add `[4.2]` to the end of `ActiveRecord::Migration`, exactly as the error message instructs.

**Comment by maxwellbenton** [comment]
Hi @kerneltux0,

Thank you for providing this feedback. We've updated this lesson's readme to include messaging about migration syntax similar to what you have suggested and believe this issue should be resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
