### ISSUE TITLE
Mechanics of Migrations version # doesn't match in IRB

### ISSUE THREAD

**Issue by DesterStorm** [learn-co-curriculum/mechanics-of-migrations#65]
The lesson is teaching about ActiveRecord::Migration[5.2], but the provided code itActiveRecord::Migration[4.2]. When I ran learn to get the list of tests, they all came back failing, and when I tried to migrate the data, it came up with an error that aborted the migration. After switching the version number to the one provided in the lesson, it was passing all the tests.

**Comment by sgharms** [comment]
Good catch! Updated.
