### ISSUE TITLE
Code-along solutions already in master

### ISSUE THREAD

**Issue by adam-mrachek** [learn-co-curriculum/mechanics-of-migrations#67]
All of the code that should be added by each student as they go through the code along is already in the repository when it's cloned down. The code that is part of the code along should be removed so students can type along instead of having to remove code first. Solutions should be in the Solution branch.

**Comment by sgharms** [comment]
I think this was addressed in https://github.com/learn-co-curriculum/mechanics-of-migrations/commit/10a6611b015c15b8ae7e17bd74848bbaaddb19dc? If not, please re-open and let me know.
