### ISSUE TITLE
AddGenderToArtist

### ISSUE THREAD

**Issue by eaud** [learn-co-curriculum/mechanics-of-migrations#7]
Just want to flag that the action of assigning a gender to an artist feels a bit tone deaf to the current politics of gender, in that said action presupposes that people must have genders. Perhaps a different example would take a less politicized stance and might future-proof this curriculum.

**Comment by AnnJohn** [comment]
Agree

**Comment by SophieDeBenedetto** [comment]
agreed, and noted.
